name: File transfer

on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_LINK:
        description: 'Link to the file that needs to be downloaded'
        required: true
        default: ''
      DOWNLOAD_NAME:
        description: 'Downloaded name'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 💥 Check Out
      uses: actions/checkout@main

    - name: 💥 Setup env
      run: |
        git config --global user.name "mochenya"
        git config --global user.email "mochen20070702@gmail.com"
        git config --global credential.helper store
        sudo timedatectl set-timezone Asia/Shanghai
        sudo rm -rf /etc/localtime
        sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: 💥 Install 7-Zip and transfer
      run: |
        export HOME=${GITHUB_WORKSPACE}
        mkdir -p ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        mkdir -p 7-zip && cd 7-zip
        wget "https://jaist.dl.sourceforge.net/project/sevenzip/7-Zip/22.01/7z2201-linux-x64.tar.xz" -O "7z2201-linux-x64.tar.xz"
        sudo chmod 0777 "7z2201-linux-x64.tar.xz"
        tar -xf "7z2201-linux-x64.tar.xz"
        sudo chmod 0777 ./7zzs
        sudo cp ./7zzs /usr/local/bin/7z
        7z --help
        cd /usr/local/bin
        sudo curl -sL "https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh" | bash
        sudo chmod 0777 transfer
        
    - name: 💥 Download file
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        aria2c -s16 -x16 -k1M "${{ github.event.inputs.DOWNLOAD_LINK }}" -o ./"${{ github.event.inputs.DOWNLOAD_NAME }}"
        
    - name: 💥 Trans
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        transfer wet ./"${{ github.event.inputs.DOWNLOAD_NAME }}"
